version: 1.0.{build}
install:
- git clone https://github.com/brondavies/letsencrypt-win-simple.git
- nuget restore letsencrypt-win-simple.sln
- cp -R packages letsencrypt-win-simple
build:
  project: letsencrypt-win-simple.sln
  verbosity: minimal
artifacts:
- path: letsencrypt-win-simple\bin\debug
  name: letsencrypt-win-simple
  type: zip