version: 1.0.{build}
install:
- nuget restore letsencrypt-win-simple.sln
- cp -R packages letsencrypt-win-simple
configuration: Release
build:
  project: letsencrypt-win-simple.sln
  verbosity: minimal

after_build:
- ps: |
    cd letsencrypt-win-simple\bin\release\
	7z a letsencrypt-win-simple.zip letsencryptcli.exe
    7z a letsencrypt-win-simple.zip letsencryptcli.exe.config
    7z a letsencrypt-win-simple.zip letsencryptcli.pdb
    7z a letsencrypt-win-simple.zip Web_Config.xml

artifacts:
- path: letsencrypt-win-simple.zip
  name: letsencrypt-win-simple